import enum


class EstadoVerificacion(str, enum.Enum):
    CREADO = "CREADO"
    DATOS_SIOX_CONSULTADOS = "DATOS_SIOX_CONSULTADOS"
    DATOS_SIOX_IMPORTADOS = "DATOS_SIOX_IMPORTADOS"
    DATOS_CAPTURADOS_MANUALMENTE = "DATOS_CAPTURADOS_MANUALMENTE"
    DATOS_NORMALIZADOS = "DATOS_NORMALIZADOS"
    INSPECCION_VISUAL_PENDIENTE = "INSPECCION_VISUAL_PENDIENTE"
    INSPECCION_VISUAL_APROBADA = "INSPECCION_VISUAL_APROBADA"
    INSPECCION_VISUAL_RECHAZADA = "INSPECCION_VISUAL_RECHAZADA"
    OBD_NO_APLICA = "OBD_NO_APLICA"
    OBD_PENDIENTE = "OBD_PENDIENTE"
    OBD_SOLICITADO = "OBD_SOLICITADO"
    OBD_RECIBIDO = "OBD_RECIBIDO"
    LISTO_PARA_PRUEBA = "LISTO_PARA_PRUEBA"
    PRUEBA_CONFIGURADA = "PRUEBA_CONFIGURADA"
    PRUEBA_EN_PROCESO = "PRUEBA_EN_PROCESO"
    PRUEBA_FINALIZADA = "PRUEBA_FINALIZADA"
    PENDIENTE_IMPRESION = "PENDIENTE_IMPRESION"
    FOLIO_SOLICITADO = "FOLIO_SOLICITADO"
    FOLIO_ASIGNADO = "FOLIO_ASIGNADO"
    IMPRESO = "IMPRESO"
    CERRADO = "CERRADO"
    ERROR_INTEGRACION = "ERROR_INTEGRACION"
    IMPRESION_FALLIDA = "IMPRESION_FALLIDA"
    FOLIO_ERROR = "FOLIO_ERROR"
    CANCELADO = "CANCELADO"


class FuenteDatos(str, enum.Enum):
    SIOX = "SIOX"
    MANUAL = "MANUAL"
    CORREGIDO_OPERADOR = "CORREGIDO_OPERADOR"


class ResultadoInspeccionVisual(str, enum.Enum):
    APROBADA = "APROBADA"
    RECHAZADA = "RECHAZADA"


class TipoPrueba(str, enum.Enum):
    DINAMICA = "DINAMICA"
    ESTATICA = "ESTATICA"
    OPACIDAD = "OPACIDAD"
    ALTERNA = "ALTERNA"


class ResultadoPruebaEnum(str, enum.Enum):
    APROBADO = "APROBADO"
    RECHAZADO = "RECHAZADO"
    ERROR = "ERROR"


class ResultadoFinal(str, enum.Enum):
    APROBADO = "APROBADO"
    RECHAZADO = "RECHAZADO"
    PENDIENTE = "PENDIENTE"
    ERROR = "ERROR"


class EstadoPrintJob(str, enum.Enum):
    PENDIENTE = "PENDIENTE"
    PROCESANDO = "PROCESANDO"
    FOLIO_SOLICITADO = "FOLIO_SOLICITADO"
    FOLIO_ASIGNADO = "FOLIO_ASIGNADO"
    IMPRESO = "IMPRESO"
    ERROR = "ERROR"
    REINTENTO = "REINTENTO"


class EstadoFolioRequest(str, enum.Enum):
    SOLICITADO = "SOLICITADO"
    ASIGNADO = "ASIGNADO"
    ERROR = "ERROR"


class EstadoFolioAssignment(str, enum.Enum):
    ASIGNADO = "ASIGNADO"
    IMPRESO = "IMPRESO"
    ANULADO = "ANULADO"
    ERROR = "ERROR"


class StationType(str, enum.Enum):
    CAPTURA = "captura"
    PRUEBA = "prueba"
    IMPRESION = "impresion"


class SyncStatus(str, enum.Enum):
    PENDING = "pending"
    SYNCING = "syncing"
    SYNCED = "synced"
    ERROR = "error"


class AccessEventResultado(str, enum.Enum):
    PERMITIDO = "PERMITIDO"
    DENEGADO = "DENEGADO"
