"""access_events para HU-007

Revision ID: 03146c98b684
Revises: 77758d2402b2
Create Date: 2026-08-04 20:29:25.154779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '03146c98b684'
down_revision: Union[str, None] = '77758d2402b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('workstation_id', sa.UUID(), nullable=True),
    sa.Column(
        'station_type',
        postgresql.ENUM('CAPTURA', 'PRUEBA', 'IMPRESION', name='station_type', create_type=False),
        nullable=True,
    ),
    sa.Column('center_id', sa.String(length=60), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('resultado', sa.Enum('PERMITIDO', 'DENEGADO', name='access_event_resultado'), nullable=False),
    sa.Column('motivo', sa.String(length=200), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['station_sessions.id'], ),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_events')
    # ### end Alembic commands ###
