"""hora_salida en Verificacion: sella el primer intento exitoso de imprimir

Revision ID: 0a6c575a2781
Revises: c6386724bf52
Create Date: 2026-08-30 15:56:56.305736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a6c575a2781'
down_revision: Union[str, None] = 'c6386724bf52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('verificaciones', sa.Column('hora_salida', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('verificaciones', 'hora_salida')
    # ### end Alembic commands ###
