"""Inventario local de folios reemplaza folio_requests/folio_assignments

Revision ID: 5519017f44f2
Revises: 6c35f3605d73
Create Date: 2026-08-25 20:32:06.605716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5519017f44f2'
down_revision: Union[str, None] = '6c35f3605d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folio_lotes',
    sa.Column('tipo_certificado', sa.Enum('PARTICULAR', 'DOBLE_CERO', 'INTENSIVO', 'RECHAZO', name='tipo_certificado'), nullable=False),
    sa.Column('folio_inicio', sa.String(length=60), nullable=False),
    sa.Column('folio_fin', sa.String(length=60), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('registrado_por', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['registrado_por'], ['cat_usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folios',
    sa.Column('lote_id', sa.UUID(), nullable=False),
    sa.Column('tipo_certificado', sa.Enum('PARTICULAR', 'DOBLE_CERO', 'INTENSIVO', 'RECHAZO', name='tipo_certificado'), nullable=False),
    sa.Column('folio', sa.String(length=60), nullable=False),
    sa.Column('orden', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('estatus', sa.Enum('DISPONIBLE', 'ASIGNADO', 'IMPRESO', 'DANADO', 'INVALIDADO', name='estado_folio'), nullable=False),
    sa.Column('verificacion_id', sa.UUID(), nullable=True),
    sa.Column('asignado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('danado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_danado', sa.Text(), nullable=True),
    sa.Column('invalidado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('motivo_invalidacion', sa.Text(), nullable=True),
    sa.Column('reemplazado_por_folio_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lote_id'], ['folio_lotes.id'], ),
    sa.ForeignKeyConstraint(['reemplazado_por_folio_id'], ['folios.id'], ),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('folio'),
    sa.UniqueConstraint('orden')
    )
    op.drop_table('folio_assignments')
    op.drop_table('folio_requests')
    # drop_table no elimina el tipo ENUM de Postgres por su cuenta —
    # quedarían huérfanos si no se limpian aquí.
    postgresql.ENUM(name='estado_folio_assignment').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='estado_folio_request').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folio_requests',
    sa.Column('verificacion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('print_job_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tipo_certificado', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('tipo_vehiculo', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('request_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('response_payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('SOLICITADO', 'ASIGNADO', 'ERROR', name='estado_folio_request'), autoincrement=False, nullable=False),
    sa.Column('folio_recibido', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('external_reference_id', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], name='folio_requests_print_job_id_fkey'),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], name='folio_requests_verificacion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='folio_requests_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('folio_assignments',
    sa.Column('verificacion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('folio_request_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('folio', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('tipo_certificado', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('asignado_por', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('estatus', postgresql.ENUM('ASIGNADO', 'IMPRESO', 'ANULADO', 'ERROR', name='estado_folio_assignment'), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['folio_request_id'], ['folio_requests.id'], name='folio_assignments_folio_request_id_fkey'),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], name='folio_assignments_verificacion_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='folio_assignments_pkey')
    )
    op.drop_table('folios')
    op.drop_table('folio_lotes')
    postgresql.ENUM(name='estado_folio').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='tipo_certificado').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
