"""print_attempts para Etapa 12

Revision ID: 6c35f3605d73
Revises: 85b52018e82e
Create Date: 2026-08-13 15:04:51.243967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c35f3605d73'
down_revision: Union[str, None] = '85b52018e82e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('print_attempts',
    sa.Column('print_job_id', sa.UUID(), nullable=False),
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('exitoso', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('print_attempts')
    # ### end Alembic commands ###
