"""esquema inicial

Revision ID: 77758d2402b2
Revises: 
Create Date: 2026-07-23 10:05:11.557924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77758d2402b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_estados_verificacion',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.Column('es_error', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('cat_parametros_sistema',
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_table('catalogos_simples',
    sa.Column('tipo', sa.String(length=60), nullable=False),
    sa.Column('clave', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clave')
    )
    op.create_index(op.f('ix_catalogos_simples_tipo'), 'catalogos_simples', ['tipo'], unique=False)
    op.create_table('sync_outbox',
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_uuid', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_status', sa.Enum('PENDING', 'SYNCING', 'SYNCED', 'ERROR', name='sync_status'), nullable=False),
    sa.Column('server_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_outbox_entity_uuid'), 'sync_outbox', ['entity_uuid'], unique=False)
    op.create_table('user_station_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('station_type', sa.Enum('CAPTURA', 'PRUEBA', 'IMPRESION', name='station_type'), nullable=False),
    sa.Column('center_id', sa.String(length=60), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('can_operate', sa.Boolean(), nullable=False),
    sa.Column('can_supervise', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('niv', sa.String(length=30), nullable=True),
    sa.Column('marca', sa.String(length=60), nullable=True),
    sa.Column('linea', sa.String(length=60), nullable=True),
    sa.Column('modelo', sa.Integer(), nullable=True),
    sa.Column('tipo_vehiculo', sa.String(length=60), nullable=True),
    sa.Column('combustible', sa.String(length=30), nullable=True),
    sa.Column('razon_social', sa.String(length=200), nullable=True),
    sa.Column('fuente_datos', sa.Enum('SIOX', 'MANUAL', 'CORREGIDO_OPERADOR', name='fuente_datos'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiculos_placa'), 'vehiculos', ['placa'], unique=False)
    op.create_table('workstations',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('station_type', sa.Enum('CAPTURA', 'PRUEBA', 'IMPRESION', name='station_type'), nullable=False),
    sa.Column('center_id', sa.String(length=60), nullable=False),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('is_centralized', sa.Boolean(), nullable=False),
    sa.Column('allowed_line_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('device_identifier', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('station_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workstation_id', sa.UUID(), nullable=False),
    sa.Column('station_type', sa.Enum('CAPTURA', 'PRUEBA', 'IMPRESION', name='station_type'), nullable=False),
    sa.Column('center_id', sa.String(length=60), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workstation_id'], ['workstations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verificaciones',
    sa.Column('vehiculo_id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('centro_id', sa.String(length=60), nullable=False),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('capture_workstation_id', sa.UUID(), nullable=True),
    sa.Column('test_workstation_id', sa.UUID(), nullable=True),
    sa.Column('print_workstation_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.Enum('CREADO', 'DATOS_SIOX_CONSULTADOS', 'DATOS_SIOX_IMPORTADOS', 'DATOS_CAPTURADOS_MANUALMENTE', 'DATOS_NORMALIZADOS', 'INSPECCION_VISUAL_PENDIENTE', 'INSPECCION_VISUAL_APROBADA', 'INSPECCION_VISUAL_RECHAZADA', 'OBD_NO_APLICA', 'OBD_PENDIENTE', 'OBD_SOLICITADO', 'OBD_RECIBIDO', 'LISTO_PARA_PRUEBA', 'PRUEBA_CONFIGURADA', 'PRUEBA_EN_PROCESO', 'PRUEBA_FINALIZADA', 'PENDIENTE_IMPRESION', 'FOLIO_SOLICITADO', 'FOLIO_ASIGNADO', 'IMPRESO', 'CERRADO', 'ERROR_INTEGRACION', 'IMPRESION_FALLIDA', 'FOLIO_ERROR', 'CANCELADO', name='estado_verificacion'), nullable=False),
    sa.Column('combustible_validado', sa.String(length=30), nullable=True),
    sa.Column('tipo_prueba_final', sa.Enum('DINAMICA', 'ESTATICA', 'OPACIDAD', 'ALTERNA', name='tipo_prueba'), nullable=True),
    sa.Column('resultado_final', sa.Enum('APROBADO', 'RECHAZADO', 'PENDIENTE', 'ERROR', name='resultado_final'), nullable=True),
    sa.Column('certificado_tipo', sa.String(length=60), nullable=True),
    sa.Column('folio_externo', sa.String(length=60), nullable=True),
    sa.Column('folio_asignado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cerrado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['capture_workstation_id'], ['workstations.id'], ),
    sa.ForeignKeyConstraint(['print_workstation_id'], ['workstations.id'], ),
    sa.ForeignKeyConstraint(['test_workstation_id'], ['workstations.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verificaciones_placa'), 'verificaciones', ['placa'], unique=False)
    op.create_table('event_log',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('evento', sa.String(length=120), nullable=False),
    sa.Column('estado_anterior', sa.Enum('CREADO', 'DATOS_SIOX_CONSULTADOS', 'DATOS_SIOX_IMPORTADOS', 'DATOS_CAPTURADOS_MANUALMENTE', 'DATOS_NORMALIZADOS', 'INSPECCION_VISUAL_PENDIENTE', 'INSPECCION_VISUAL_APROBADA', 'INSPECCION_VISUAL_RECHAZADA', 'OBD_NO_APLICA', 'OBD_PENDIENTE', 'OBD_SOLICITADO', 'OBD_RECIBIDO', 'LISTO_PARA_PRUEBA', 'PRUEBA_CONFIGURADA', 'PRUEBA_EN_PROCESO', 'PRUEBA_FINALIZADA', 'PENDIENTE_IMPRESION', 'FOLIO_SOLICITADO', 'FOLIO_ASIGNADO', 'IMPRESO', 'CERRADO', 'ERROR_INTEGRACION', 'IMPRESION_FALLIDA', 'FOLIO_ERROR', 'CANCELADO', name='estado_verificacion'), nullable=True),
    sa.Column('estado_nuevo', sa.Enum('CREADO', 'DATOS_SIOX_CONSULTADOS', 'DATOS_SIOX_IMPORTADOS', 'DATOS_CAPTURADOS_MANUALMENTE', 'DATOS_NORMALIZADOS', 'INSPECCION_VISUAL_PENDIENTE', 'INSPECCION_VISUAL_APROBADA', 'INSPECCION_VISUAL_RECHAZADA', 'OBD_NO_APLICA', 'OBD_PENDIENTE', 'OBD_SOLICITADO', 'OBD_RECIBIDO', 'LISTO_PARA_PRUEBA', 'PRUEBA_CONFIGURADA', 'PRUEBA_EN_PROCESO', 'PRUEBA_FINALIZADA', 'PENDIENTE_IMPRESION', 'FOLIO_SOLICITADO', 'FOLIO_ASIGNADO', 'IMPRESO', 'CERRADO', 'ERROR_INTEGRACION', 'IMPRESION_FALLIDA', 'FOLIO_ERROR', 'CANCELADO', name='estado_verificacion'), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('modulo', sa.String(length=30), nullable=False),
    sa.Column('detalle_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspeccion_visual',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('resultado', sa.Enum('APROBADA', 'RECHAZADA', name='resultado_inspeccion_visual'), nullable=False),
    sa.Column('checklist_json', sa.JSON(), nullable=False),
    sa.Column('causales_rechazo', sa.JSON(), nullable=True),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('integration_logs',
    sa.Column('verificacion_id', sa.UUID(), nullable=True),
    sa.Column('integration_name', sa.String(length=60), nullable=False),
    sa.Column('direction', sa.Enum('REQUEST', 'RESPONSE', name='integration_direction'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('OK', 'ERROR', name='integration_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_jobs',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=60), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'FOLIO_SOLICITADO', 'FOLIO_ASIGNADO', 'IMPRESO', 'ERROR', 'REINTENTO', name='estado_print_job'), nullable=False),
    sa.Column('requiere_folio', sa.Boolean(), nullable=False),
    sa.Column('folio_externo', sa.String(length=60), nullable=True),
    sa.Column('intentos', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('printed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_obd_sbd',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('aplica', sa.Boolean(), nullable=False),
    sa.Column('solicitado_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recibido_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resultado', sa.Enum('APROBADO', 'RECHAZADO', 'ERROR', name='resultado_obd_sbd_enum'), nullable=True),
    sa.Column('codigos_error', sa.JSON(), nullable=True),
    sa.Column('datos_raw', sa.JSON(), nullable=True),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_prueba',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('tipo_prueba', sa.Enum('DINAMICA', 'ESTATICA', 'OPACIDAD', 'ALTERNA', name='tipo_prueba_resultado'), nullable=False),
    sa.Column('combustible', sa.String(length=30), nullable=False),
    sa.Column('resultado', sa.Enum('APROBADO', 'RECHAZADO', 'ERROR', name='resultado_prueba_enum'), nullable=True),
    sa.Column('valores_medidos_json', sa.JSON(), nullable=True),
    sa.Column('limites_aplicados_json', sa.JSON(), nullable=True),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.Column('linea_id', sa.Integer(), nullable=False),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('siox_consultas',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=False),
    sa.Column('url_consulta', sa.Text(), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_raw', sa.JSON(), nullable=True),
    sa.Column('response_normalized', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('EXITOSA', 'SIN_DATOS', 'ERROR', name='estado_siox_consulta'), nullable=False),
    sa.Column('consultado_por', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folio_requests',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('print_job_id', sa.UUID(), nullable=True),
    sa.Column('tipo_certificado', sa.String(length=60), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=60), nullable=True),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('response_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('SOLICITADO', 'ASIGNADO', 'ERROR', name='estado_folio_request'), nullable=False),
    sa.Column('folio_recibido', sa.String(length=60), nullable=True),
    sa.Column('external_reference_id', sa.String(length=120), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_jobs.id'], ),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folio_assignments',
    sa.Column('verificacion_id', sa.UUID(), nullable=False),
    sa.Column('folio_request_id', sa.UUID(), nullable=False),
    sa.Column('folio', sa.String(length=60), nullable=False),
    sa.Column('tipo_certificado', sa.String(length=60), nullable=False),
    sa.Column('asignado_por', sa.String(length=120), nullable=True),
    sa.Column('estatus', sa.Enum('ASIGNADO', 'IMPRESO', 'ANULADO', 'ERROR', name='estado_folio_assignment'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['folio_request_id'], ['folio_requests.id'], ),
    sa.ForeignKeyConstraint(['verificacion_id'], ['verificaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folio_assignments')
    op.drop_table('folio_requests')
    op.drop_table('siox_consultas')
    op.drop_table('resultados_prueba')
    op.drop_table('resultados_obd_sbd')
    op.drop_table('print_jobs')
    op.drop_table('integration_logs')
    op.drop_table('inspeccion_visual')
    op.drop_table('event_log')
    op.drop_index(op.f('ix_verificaciones_placa'), table_name='verificaciones')
    op.drop_table('verificaciones')
    op.drop_table('station_sessions')
    op.drop_table('workstations')
    op.drop_index(op.f('ix_vehiculos_placa'), table_name='vehiculos')
    op.drop_table('vehiculos')
    op.drop_table('user_station_permissions')
    op.drop_index(op.f('ix_sync_outbox_entity_uuid'), table_name='sync_outbox')
    op.drop_table('sync_outbox')
    op.drop_index(op.f('ix_catalogos_simples_tipo'), table_name='catalogos_simples')
    op.drop_table('catalogos_simples')
    op.drop_table('cat_parametros_sistema')
    op.drop_table('cat_estados_verificacion')
    # ### end Alembic commands ###
