"""Vehiculo: propietario/domicilio, tarjeta de circulacion, PBV y traccion

Revision ID: d029fa2bd196
Revises: 0a6c575a2781
Create Date: 2026-08-30 16:02:29.414870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd029fa2bd196'
down_revision: Union[str, None] = '0a6c575a2781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehiculos', sa.Column('tarjeta_circulacion', sa.String(length=60), nullable=True))
    op.add_column('vehiculos', sa.Column('propietario_estado', sa.String(length=60), nullable=True))
    op.add_column('vehiculos', sa.Column('propietario_municipio', sa.String(length=100), nullable=True))
    op.add_column('vehiculos', sa.Column('propietario_codigo_postal', sa.String(length=10), nullable=True))
    op.add_column('vehiculos', sa.Column('propietario_colonia', sa.String(length=100), nullable=True))
    op.add_column('vehiculos', sa.Column('propietario_calle', sa.String(length=150), nullable=True))
    op.add_column('vehiculos', sa.Column('propietario_numero_exterior', sa.String(length=20), nullable=True))
    op.add_column('vehiculos', sa.Column('pbv', sa.String(length=30), nullable=True))
    op.add_column('vehiculos', sa.Column('traccion', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehiculos', 'traccion')
    op.drop_column('vehiculos', 'pbv')
    op.drop_column('vehiculos', 'propietario_numero_exterior')
    op.drop_column('vehiculos', 'propietario_calle')
    op.drop_column('vehiculos', 'propietario_colonia')
    op.drop_column('vehiculos', 'propietario_codigo_postal')
    op.drop_column('vehiculos', 'propietario_municipio')
    op.drop_column('vehiculos', 'propietario_estado')
    op.drop_column('vehiculos', 'tarjeta_circulacion')
    # ### end Alembic commands ###
