"""capacidad_dinamometro_kg_por_estacion

Revision ID: d1451a3c9689
Revises: f6b3d8e1a9c2
Create Date: 2026-09-04 08:29:29.239111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1451a3c9689'
down_revision: Union[str, None] = 'f6b3d8e1a9c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workstations', sa.Column('capacidad_dinamometro_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workstations', 'capacidad_dinamometro_kg')
    # ### end Alembic commands ###
