"""prorroga_semestre

Revision ID: d51e439f9236
Revises: d1451a3c9689
Create Date: 2026-09-04 08:57:09.592996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd51e439f9236'
down_revision: Union[str, None] = 'd1451a3c9689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prorroga_semestre',
    sa.Column('orden', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('fecha_final', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orden')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prorroga_semestre')
    # ### end Alembic commands ###
